[toolchain]
anchor_version = "0.29.0"
[features]
seeds = false
skip-lint = false

[programs.localnet]
nova_staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
nova_staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.mainnet]
nova_staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
<<<<<<< HEAD
cluster = "devnet"
=======
cluster = "https://api.devnet.solana.com"
>>>>>>> fce5ed1 (Fix Solana SBF rustc 1.75 compatibility (borsh + proc-macro-crate patches))
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
